version: "3.7"
services:
  caddy:
    image: caddy
    container_name: caddy
    restart: uless-stopped
    ports:
      - "80:80"
      - "443:443"
    enviroment:
      - MY_DOMAIN
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
networks:
  default:
    external:
      name: $DOCKER_MY_NETWORK
